//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EasyBar.rc
//
#define IDR_XPMANIFEST                  1
#define IDD_PLAYER                      101
#define IDR_MAINMENU                    102
#define IDD_VIDEO                       102
#define IDI_MAIN                        103
#define IDR_MAINACCEL                   110
#define IDD_ABOUT                       111
#define IDD_PROPERTIES                  117
#define IDD_PP_GENERAL                  118
#define IDD_PP_FILTERS                  120
#define IDD_PP_CONTENT                  121
#define IDI_FILE                        122
#define IDD_OPACITY                     123
#define IDD_EXTERNALFILTERS             128
#define IDD_FAVORITES                   135
#define IDD_COLORS                      136
#define IDB_BALANCENORMAL               138
#define IDB_NEXTFILE                    139
#define IDB_PAUSE                       140
#define IDB_PLAY                        141
#define IDB_PREVIOUSFILE                142
#define IDB_SOUNDOFF                    143
#define IDB_SOUNDON                     144
#define IDB_STEPBACKWARD                145
#define IDB_STEPFORWARD                 146
#define IDB_LOGO                        148
#define IDD_FULLSCREENVIDEOMODE         149
#define IDD_ASSOCIATIONS                150
#define IDD_TIMEINTERVALS               151
#define IDD_URL                         152
#define IDD_PLAYER_VW                   153
#define IDB_CHECKMARK                   155
#define IDB_RADIOCHECKMARK              156
#define IDD_PLAYLIST                    159
#define IDB_ACTIVEITEM                  160
#define IDD_PP_ADJUSTMENTS              160
#define IDR_PLMENU                      161
#define IDR_PLACCEL                     162
#define IDS_CREDITS                     165
#define IDC_STCICON                     1012
#define IDC_STCNAME                     1013
#define IDC_STCCOP                      1014
#define IDC_BTNOK                       1016
#define IDC_BTNVIDEO                    1017
#define IDC_BTNAUDIO                    1018
#define IDC_TABPROP                     1022
#define IDC_BTNCLOSE                    1023
#define IDC_BTNPROP                     1026
#define IDC_STCFIL                      1028
#define IDC_BTNREFR                     1029
#define IDC_LSTFILTERS                  1031
#define IDC_STCFILE                     1032
#define IDC_EDTFN                       1035
#define IDC_STCMT                       1036
#define IDC_STCML                       1037
#define IDC_STCVS                       1039
#define IDC_STCLOC                      1040
#define IDC_STCEXT                      1041
#define IDC_STCFS                       1042
#define IDC_STCGLN2                     1043
#define IDC_EDTLOC                      1044
#define IDC_EDTEXT                      1045
#define IDC_EDTFS                       1046
#define IDC_EDTMT                       1047
#define IDC_EDTML                       1049
#define IDC_EDTVS                       1050
#define IDC_STCGLN3                     1051
#define IDC_STCCR                       1052
#define IDC_STCATT                      1053
#define IDC_EDTCR                       1054
#define IDC_BTNCANCEL                   1054
#define IDC_EDTAT                       1055
#define IDC_STCCL                       1055
#define IDC_STC1P                       1056
#define IDC_STC100P                     1057
#define IDC_SLDOL                       1058
#define IDC_STCLIC                      1059
#define IDC_STCCLIP                     1060
#define IDC_EDTCLIP                     1061
#define IDC_STCAUTH                     1062
#define IDC_EDTAUTH                     1063
#define IDC_EDTCOP                      1065
#define IDC_STCEM                       1066
#define IDC_STCRAT                      1066
#define IDC_EDTDESC                     1067
#define IDC_STCDESC                     1068
#define IDC_EDTRAT                      1069
#define IDC_EDTMI                       1070
#define IDC_EBSLDSEEK                   1070
#define IDC_EBSLDVOL                    1071
#define IDC_LSTAF                       1071
#define IDC_STCMI                       1071
#define IDC_EBSLDBAL                    1072
#define IDC_STCRDSF                     1072
#define IDC_LSTSF                       1073
#define IDC_BTNADD                      1074
#define IDC_BTNREM                      1075
#define IDC_CHKUEF                      1076
#define IDC_STCAV                       1077
#define IDC_STCSEL                      1078
#define IDC_EBDMAIN                     1078
#define IDC_STCFILES                    1079
#define IDC_BTNACF                      1080
#define IDC_BTNSEL                      1083
#define IDC_BTNCA                       1085
#define IDC_STCS                        1087
#define IDC_CBOITEMS                    1088
#define IDC_STCI                        1090
#define IDC_STCC                        1091
#define IDC_STCCOLOR                    1093
#define IDC_EBFMAIN                     1097
#define IDC_EBBMUT                      1098
#define IDC_EBBBN                       1099
#define IDC_EBBPF                       1100
#define IDC_EBBSB                       1101
#define IDC_STCLOGO                     1101
#define IDC_EBBPP                       1102
#define IDC_EBBSF                       1103
#define IDC_STCVM                       1103
#define IDC_EBBNF                       1104
#define IDC_CHKCVM                      1104
#define IDC_CBOVM                       1105
#define IDC_STCFT                       1106
#define IDC_LSTFT                       1107
#define IDC_STCCLN1                     1113
#define IDC_LVFILES                     1116
#define IDC_BTNMU                       1118
#define IDC_BTNMD                       1119
#define IDC_STCLJ                       1119
#define IDC_SPNSTI                      1120
#define IDC_EDTSTI                      1121
#define IDC_STCJUMP                     1122
#define IDC_EDTJTI                      1123
#define IDC_SPNJTI                      1124
#define IDC_STCSTEP                     1125
#define IDC_EDTLJTI                     1126
#define IDC_SPNLJTI                     1127
#define IDC_BTNDEFAULT                  1129
#define IDC_STCS1                       1130
#define IDC_STCS2                       1131
#define IDC_STCEU                       1131
#define IDC_STCS3                       1132
#define IDC_EDTURL                      1133
#define IDC_STCALN1                     1135
#define IDC_STCGLN1                     1136
#define IDC_STCFLN1                     1137
#define IDC_STCFI                       1138
#define IDC_STCFCLSID                   1139
#define IDC_STCFM                       1140
#define IDC_EDTFCLSID                   1141
#define IDC_EDTFM                       1142
#define IDC_LSTPL                       1144
#define IDC_CHKP                        1145
#define IDC_BTNIMGS                     1146
#define IDC_BTNPLS                      1147
#define IDC_BTNCRED                     1147
#define IDC_EDTCRED                     1148
#define IDC_BTNRESET                    1149
#define IDC_STCAS                       1150
#define IDC_BTNSAS                      1151
#define IDC_CBOAS                       1152
#define IDC_BTNEVS                      1153
#define IDC_BTNSVS                      1153
#define IDC_CBOVS                       1154
#define IDM_FILE_EXIT                   40003
#define IDM_HELP_ABOUT                  40009
#define IDM_FILE_CLOSE                  40011
#define IDM_ZOOM_HALFSIZE               40014
#define IDM_ZOOM_NORMALSIZE             40015
#define IDM_ZOOM_DOUBLESIZE             40016
#define IDM_ONTOP_NEVER                 40019
#define IDM_ONTOP_ALWAYS                40020
#define IDM_ONTOP_WHILEPLAYING          40021
#define IDM_WB_NORMALWINDOW             40022
#define IDM_WB_TOOLWINDOW               40023
#define IDM_VIEW_MAINCONTROLS           40027
#define IDM_FILE_NEWPLAYER              40030
#define IDM_FILE_PROPERTIES             40032
#define IDM_PAS_SCREENCENTER            40034
#define IDM_PAS_RESTOREPREVIOUS         40035
#define IDM_PAS_RANDOM                  40036
#define IDM_SAE_WAVESREVERB             40039
#define IDM_DMO_USEDMO                  40040
#define IDM_SAE_GARGLE                  40041
#define IDM_SAE_DISTORTION              40042
#define IDM_SAE_COMPRESSOR              40043
#define IDM_SAE_ECHO                    40044
#define IDM_SAE_FLANGER                 40045
#define IDM_SAE_CHORUS                  40046
#define IDM_OPACITY_100                 40047
#define IDM_OPACITY_75                  40048
#define IDM_OPACITY_50                  40049
#define IDM_OPACITY_25                  40050
#define IDM_OPACITY_CUSTOM              40051
#define IDM_PLAYBACK_FRAMESTEP          40052
#define IDM_FILE_CLOSEWINDOW            40053
#define IDM_VIEW_TRAYICON               40054
#define IDM_VOLUME_INCREASE             40055
#define IDM_VOLUME_DECREASE             40056
#define IDM_BALANCE_LEFT                40057
#define IDM_BALANCE_RIGHT               40058
#define IDM_VOLUME_MUTE                 40059
#define IDM_PB_ADV_EXTFLT               40064
#define IDM_INTERFACE_USESYSTEMCOLORS   40071
#define IDM_AP_CLOSEWINDOW              40072
#define IDM_AP_EXIT                     40073
#define IDM_AP_STANDBY                  40074
#define IDM_AP_HIBERNATE                40075
#define IDM_AP_SHUTDOWN                 40076
#define IDM_AP_LOGOFF                   40077
#define IDM_AP_DONOTHING                40078
#define IDM_FILE_FAVORITES              40080
#define IDM_INTERFACE_DEFINECOLORS      40081
#define IDM_FILE_SAVEPLAYLISTAS         40087
#define IDM_PB_ADV_AGTROT               40089
#define IDM_FULLSCREEN_VIDEOMODE        40099
#define IDM_FILE_MULTIPLEINSTANCES      40100
#define IDM_FILE_ASSOCIATIONS           40101
#define IDM_SAE_I3DL2REVERB             40104
#define IDM_SAE_PARAMEQ                 40105
#define IDM_AR_DEFAULT                  40110
#define IDM_AR_43                       40111
#define IDM_AR_54                       40112
#define IDM_AR_169                      40113
#define IDM_AR_KEEPASPECTRATIO          40121
#define IDM_HELP_HELPTOPICS             40122
#define IDM_TB_DISPLAYFULLPATH          40124
#define IDM_TB_DISPLAYFILENAMEONLY      40125
#define IDM_TB_DONOTCHANGETITLE         40126
#define IDM_FILE_OPENFILES              40127
#define IDM_FILE_ADDFILES               40128
#define IDM_FILE_OPENDIRECTORY          40129
#define IDM_FILE_ADDDIRECTORY           40130
#define IDM_FILE_SAVEFILEAS             40131
#define IDM_FILE_REMEMBERPLAYLIST       40132
#define IDM_FILE_DELETEFROMPLAYLIST     40135
#define IDM_REPEAT_REPEATOFF            40136
#define IDM_REPEAT_REPEATALL            40137
#define IDM_REPEAT_REPEATONE            40138
#define IDM_PLAYBACK_SHUFFLE            40139
#define IDM_RATE_DECREASE               40141
#define IDM_RATE_INCREASE               40142
#define IDM_PLAYBACK_PREVIOUSFILE       40149
#define IDM_PLAYBACK_NEXTFILE           40150
#define IDM_PLAYBACK_PLAYPAUSE          40151
#define IDM_PLAYBACK_STOP               40152
#define IDM_FULLSCREEN_FULLSCREENNORMAL 40154
#define IDM_BALANCE_NORMAL              40155
#define IDM_RATE_NORMAL                 40156
#define IDM_SEEK_DEFINETIMEINTERVALS    40160
#define IDM_SEEK_STEPBACKWARD           40161
#define IDM_SEEK_STEPFORWARD            40162
#define IDM_SEEK_JUMPBACKWARD           40163
#define IDM_SEEK_JUMPFORWARD            40164
#define IDM_SEEK_LONGJUMPBACKWARD       40165
#define IDM_SEEK_LONGJUMPFORWARD        40166
#define IDM_SEEK_REWIND                 40167
#define IDM_SEEK_SEEKBYKEYFRAMES        40168
#define IDM_OPACITY_OPAQUEONFOCUS       40169
#define IDM_FILE_ADDURL                 40170
#define IDM_AS_RESUMEPLAYBACK           40173
#define IDM_FILE_REOPENCURRENT          40174
#define IDM_PLAYBACK_SAVECURRENTFRAME   40175
#define IDM_VIEW_PLAYLIST               40177
#define IDM_SELECTION_DELETE            40184
#define IDM_MISC_FIND                   40185
#define IDM_MISC_CLEARPLAYLIST          40186
#define ID_OPENDIRECTORY_OPENDIRECTORY  40191
#define IDM_OPENDIRECTORY_OPENDIRECTORY 40192
#define IDM_OD_OPENDIRECTORY            40193
#define ID_OPENDIRECTORY_OPENDIRECTORY40194 40194
#define ID_OD_OPENDIRECTORY_II          40195
#define ID_ADDDIRECTORY_ADDDIRECTORY    40196
#define IDM_AD_ADDDIRECTORY             40197
#define ID_ADDDIRECTORY_ADDDIRECTORY40198 40198
#define IDM_AD_ADDDIRECTORY_II          40199
#define IDM_OD_OPENDIRECTORY_II         40200
#define ID_SELECTION_MOVEUP             40201
#define ID_SELECTION_MOVEDOWN           40202
#define IDM_SELECTION_MOVEUP            40203
#define IDM_SELECTION_MOVEDOWN          40204
#define ID_MANAGE_OPENFILE              40210
#define ID_MANAGE_HIDE                  40211
#define IDM_MANAGE_HIDE                 40212

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         40213
#define _APS_NEXT_CONTROL_VALUE         1153
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
